CAR:
  EPS: 0.4
  MIN_SAMPLES: 15
  RADIUS_EMPTY_SPACE_CHECK: 0.5
  RADIUS_RAYCAST: 0.3
  MAX_WIDTH: 5
  MAX_LENGTH: 6
  MAX_HEIGTH: 2
  MIN_HEIGTH: 0.2
  MIN_LENGTH: 1
  NUM_OF_FRAMES_IN_FUTURE: 4
  EGO_DELETE_RADIUS: 1.5
  

PEDESTRIAN:
  EPS: 0.3
  MIN_SAMPLES: 40
  RADIUS_EMPTY_SPACE_CHECK: 0.1
  RADIUS_RAYCAST: 0.3
  MAX_WIDTH: 2
  MAX_LENGTH: 2
  MAX_HEIGTH: 2.2
  MIN_HEIGTH: 0.8
  MIN_LENGTH: 0.3
  NUM_OF_FRAMES_IN_FUTURE: 7
  EGO_DELETE_RADIUS: 1.5
  